### ISSUE TITLE
Question on Static Animation

### ISSUE THREAD

**Issue by raitucarp** [fogleman/primitive#87]
This project is awesome.. I have a question on Static Animation. What parameters should I use to get static animation result?

Thank you

**Comment by bradydowling** [comment]
From what I understand, you need to create your own static animation by patching together multiple files you create with the same arguments (since the output will be random and slightly different every time).

I haven't found a method for creating a `.gif` from several different `.png` or `.jpg` files yet but I'm sure there are a ton. Feel free to paste in a command here if you find one that works well.
